#ARCHIVO DE PRUEBA PARA UN FLUJO DE TRABAJO DE GITHUB
name: archivo de deploy para bucket s3 con angular

on:
  push:
    branches:
      - main


jobs:
    log-message:
      runs-on: ubuntu-latest

      steps:
       - name: Print messsage
         run: echo "Workflow ejecutado"